# Generated by Django 6.0.4 on 2026-06-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_type_customerprofile_providerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_complted',
            field=models.BooleanField(default=False),
        ),
    ]
