# Generated by Django 6.0.4 on 2026-06-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_complted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_complted',
            new_name='profile_completed',
        ),
    ]
