# Generated by Django 6.0.4 on 2026-06-24 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_profile_complted_user_profile_completed'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.skills'),
        ),
    ]
