# Generated by Django 6.0.4 on 2026-06-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_providerprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
