# Generated by Django 6.0.4 on 2026-06-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_providerprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
